# generated by configure / remove this line to disable regeneration
prefix="/home/zonca/zonca/p/software/healpy/build/temp.linux-x86_64-3.7"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/zonca/zonca/p/software/healpy/build/temp.linux-x86_64-3.7/sharp/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="//home/zonca/zonca/p/software/healpy/healpixsubmodule/src/common_libraries/libsharp"
package="libsharp"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "libsharp"
;; --help) pkg-config --help ; echo Buildscript Of "libsharp Library"
;; --modversion|--version) echo "1.0.0"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-lsharp -lm"
       :
;; --cflags) echo -I${includedir} ""
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
